apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-hbc3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-hbc3
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-hbc3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-hbc3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-hbc3
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-atmd-tenant/dotnet-component/devfile-sample-dotnet60-basic-hbc3@sha256:8dfeccffac5522fd4331d36aa3ca816224fda95b0f31158fa802c084e514033e
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
